### ISSUE TITLE
ical.js v1.3.0 breaks a test

### ISSUE THREAD

**Issue by mifi** [mifi/ical-expander#11] opened 2019-08-12 16:17 UTC
```
  1)  should parse issue 285 case correctly:
      AssertionError: [] deepEqual [ '2017-01-18T08:00:00.000Z' ]
      + expected - actual
      -[]
      +[
      +  "2017-01-18T08:00:00.000Z"
      +]
      
      at Context.<anonymous> (test/ical-expander.js:49:10)
```

See:
- https://github.com/mozilla-comm/ical.js/issues/351
- https://github.com/mozilla-comm/ical.js/releases/tag/v1.3.0

**Comment by radarfox** [comment] 2020-04-15 09:25
This looks like a duplicate of #14

**Comment by mifi** [comment] 2020-04-24 14:14
I think this one should be fixed now

**Comment by radarfox** [comment] 2020-04-26 13:23
Yes it should, version 3 works for me in similar tests.

**Closed as completed** 2020-11-03 12:06 UTC
